//Window
#macro INITIAL_WIN_WIDTH    320
#macro INITIAL_WIN_HEIGHT   240
#macro INITIAL_WIN_SCALE    2

#macro INTERNAL_RESOLUTION_UPSCALING_ENABLE false
#macro INTERNAL_RESOLUTION_UPSCALING_METHOD 0
#macro INTERNAL_RESOLUTION_SCALE            4

//Camera
#macro CAMERA_FOLLOW_SPEED 0.3

//Textboxes
#macro TEXTBOX_GROWSPEED    8
#macro TEXTBOX_GROWSNAP     4
#macro TEXTBOX_SPEED_NORMAL 3
#macro TEXTBOX_SPEED_FAST   0

//Transitions
enum TRANSITIONS_TYPES {
	FADE_TO_BLACK
}
enum TRANSITIONS_PHASES {
	STARTING,
    WAITING,
    ENDING
}