//Window
#macro INITIAL_WIN_WIDTH    320
#macro INITIAL_WIN_HEIGHT   240
#macro INITIAL_WIN_SCALE    2

#macro INTERNAL_RESOLUTION_UPSCALING_ENABLE true
#macro INTERNAL_RESOLUTION_UPSCALING_METHOD 1
#macro INTERNAL_RESOLUTION_SCALE            4 